### ISSUE TITLE
Update parsing functions/classes to handle latest IIIF 3.0 avalon-bundle manifest

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon-iiif-player#22]
### Description
Update the parsing code to handle updated IIIF 3.0 manifest object structure.

### Done Looks Like
- Standalone player consumes new manifest successfully.
- Standalone player renders proper nested navigation.
- Standalone player navigation links successfully navigate the MEJS player.
- Unit Tests are written (new Jest unit test issue here)

### Tasks 
- [x] import a local latest 3.0 manifest file
- [x] Update parsing code to render proper nested structure.
- [x] Verify navigation links are properly displayed.
- [x] Verify MEJS navigation works from new nested structure links.
- [x] Write unit tests

### Related work
- ( remove karma / install jest )

**Comment by adamjarling** [comment]
@mcwhitaker I finished up the Jest ticket, so pulling this in to get started fyi.
