### ISSUE TITLE
Update unit testing framework to Jest

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon-iiif-player#23]
### Description
Remove karma/jasmine unit testing dependencies in favor of Jest.   Jest is better.

### Done Looks Like
- Karma / Jasmine packages removed
- Jest installed and configured

### Tasks
- [x] Remove Karma / Jasmine packages.
- [x] Remove previous unit tests.
- [x] Install Jest package and configure for our webpacker instance
- [x] Write a few tests to verify all works.
