### ISSUE TITLE
Simplify NPM/yarn exportable IIIF Media Player component repos

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon-iiif-player#29]
### Description
Currently there are 2 separate repositories for the IIIF Media Player:

1. The development repository (this repo)
2. the npm package wrapper repository (react-iiif-media-player)

This setup (experimental), makes development within Avalon bundle tricky, so we should consolidate these two repositories and document how any developer can make updates easily, which can be used by Avalon Bundle.

### Done Looks Like
- This repository can handle both development, and also the exporting of an npm package.
- The npm/yarn packages are consolidated and updated.  One must be deleted.
- Documentation is written for a different ticket.

### Tasks
- [x] Eject create-react-app build tool, to allow our custom configurations. (tried but didn't work)
- [x] Re-factor application to support both development setup, and also npm package setup. (tried but didn't work)
- [x] Test importing locally via yarn file path for development.
- [ ] Update documentation for this repository and at NPM / Yarn. (create a new ticket for this)

**Comment by adamjarling** [comment]
@mcwhitaker @joncameron @davidschober I pulled this into the sprint as it seems pretty important to get this process simplified and available to the team.

**Comment by adamjarling** [comment]
So, after attempting a few unsuccessful ways of creating a npm exportable package from this repository (`avalon-iiif-player`) through ejecting `create-react-app` bootstrapper, for now the best, most direct path forward is to bypass this `avalon-iiif-player` repo and just use `react-iiif-media-player` for current dev work and PRs.

I've customized `react-iiif-media-player` so the previous testing environment works, and figured out how to add the package via `yarn` either locally or pointing at a GitHub branch.   It's still not the most direct process of developing for `avalon-bundle`, but the trade-off benefit (as discussed with @cjcolvar ) is that the separated IIIF Player component is available  to others using React, in a pretty straightforward way.    Not tied to Hyrax, Samvera or anything else.
