### ISSUE TITLE
Update UI and style dependencies

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon-iiif-player#9]
### Description
Update UI for upcoming IIIF A/V working groups in LA and Toronto.

### Tasks
- [x] Remove semantic-ui dependency
- [x] Create custom css base including responsive
- [x] Incorporate basic Avalon branding
- [x] Add Bootstrap 4 as a dev dependency
- [x] Update application structure - remove `avalon` directory for more generic reference to the IIIF player.
